#!/bin/bash
i="1"
nrItems="1000"

while [ $i -lt $nrItems ]
do
curl -X POST "${URL}" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"id\": \"${i}\", \"name\": \"autogenerated\", \"description\": \"an autogenerated todo\"}"
i=$[$i+1]
done